name: Run Tests

on:
  push:
    branches:
      - 'master'
      - '*.x'
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v4

    - name: "Setup PHP"
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        tools: composer:v2
        coverage: xdebug
        extensions: dom, curl, libxml, mbstring, zip, xdebug

    - name: "Setup PHPUnit environment"
      run: cp phpunit.xml.dist phpunit.xml && cp workbench/.env.example workbench/.env && touch workbench/database/database.sqlite

    - name: "Run PHPUnit tests"
      run: vendor/bin/phpunit --display-warnings
